# Policy for: .github/workflows/release-tag.yml
issuer: https://token.actions.githubusercontent.com
subject: repo:DataDog/dd-openfeature-provider-swift:pull_request

claim_pattern:
  base_ref: main
  event_name: pull_request
  head_ref: release/[0-9]+\.[0-9]+\.[0-9]+
  job_workflow_ref: DataDog/dd-openfeature-provider-swift/\.github/workflows/release-tag\.yml@refs/heads/develop
  ref: refs/heads/main
  repository: DataDog/dd-openfeature-provider-swift

permissions:
  contents: write
  pull_requests: write
