# Policy for: .github/workflows/release-prepare.yml
issuer: https://token.actions.githubusercontent.com
subject: repo:DataDog/dd-openfeature-provider-swift:ref:refs/heads/develop

claim_pattern:
  event_name: workflow_dispatch
  job_workflow_ref: DataDog/dd-openfeature-provider-swift/\.github/workflows/release-prepare\.yml@refs/heads/develop
  ref: refs/heads/develop
  repository: DataDog/dd-openfeature-provider-swift

permissions:
  contents: write
  pull_requests: write
